package com.datn.topfood.util.enums;

public enum MessageType {
    ADD_MEMBER,
    SEND,
    KICK_MEMBER,
    TRANSFER_CONVERSATION,
    UPDATE_CONVERSATION,
    INFO_CONVERSATION,
    REACT_MESSAGE,
    REMOVE_MESSAGE,
    CREATE_CONVERSATION,
    DELETE_CONVERSATION,
    LIST_CONVERSATION,
    LIST_MESSAGE,
}
